services:
  next:
    image: node:20.16.0
    container_name: next
    working_dir: /app/next
    tty: true
    volumes:
      - ./next:/app/next
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"

  nest:
    image: node:20.16.0
    container_name: nest
    working_dir: /app/nest
    tty: true
    volumes:
      - ./nest:/app/nest
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3001:3000"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    hostname: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: db_admin
      TZ: Asia/Tokyo
    command: start-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    hostname: postgres
    restart: unless-stopped
    shm_size: 128mb
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: db_admin