services:
  next:
    image: node:20.16.0
    container_name: next
    working_dir: /app/next
    tty: true
    volumes:
      - ./next:/app/next
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"

  nest:
    image: node:20.16.0
    container_name: nest
    working_dir: /app/nest
    tty: true
    volumes:
      - ./nest:/app/nest
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3001:3000"
